apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: demo-app
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: demo-app
  podMetricsEndpoints:
    - targetPort: 3000
      path: /metrics
